version: '2'
services:
  jenkins:
    build:
      context: .
      args:
      - UID=1001
      - GID=1001
    restart: always
    ports:
    - 8080:8080
    - 50000:50000
    volumes:
    - /home/jenkins/jenkins_home:/var/jenkins_home
